// Hardcoded constituency data for the location-aware sidebar.
// 16 major Lok Sabha PCs covering states across India. Numbers reflect the
// 2024 General Election cycle. Manual curation acceptable for hackathon scope.
// Sources: ECI press notes, MyNeta affidavits, Wikipedia. Verify before any
// production use — this snapshot may go stale.

export interface CandidateAffidavit {
  name: string;
  party: string;
  partyShort: string;
  educationLevel: string;
  declaredAssetsCrore: number;
  liabilitiesLakh: number;
  criminalCases: number;
  age: number;
}

export interface HistoricalResult {
  year: number;
  winner: string;
  winnerParty: string;
  turnoutPercent: number;
  marginPercent: number;
}

export interface Constituency {
  id: string;                  // 3-letter ECI code
  name: string;                // PC name
  state: string;
  stateCode: string;
  lon: number;
  lat: number;
  totalElectors: number;       // ~ for most recent cycle
  pollingPhase: number;        // 1..7 for 2024 LS
  pollingDate: string;         // ISO date
  countingDate: string;        // ISO date
  sittingMP: string;           // post-2024 result
  sittingMPParty: string;
  candidates2024: CandidateAffidavit[];
  history: HistoricalResult;
  alternateIDs: string[];      // accepted at booth
  boothFinderURL: string;
  hot?: boolean;               // visually marked on map
}

export const CONSTITUENCIES: Constituency[] = [
  {
    id: "VAR",
    name: "Varanasi",
    state: "Uttar Pradesh",
    stateCode: "UP",
    lon: 82.97,
    lat: 25.32,
    totalElectors: 1995591,
    pollingPhase: 7,
    pollingDate: "2024-06-01",
    countingDate: "2024-06-04",
    sittingMP: "Narendra Modi",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Narendra Modi",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Master's",
        declaredAssetsCrore: 3.02,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 73,
      },
      {
        name: "Ajay Rai",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "Graduate",
        declaredAssetsCrore: 13.74,
        liabilitiesLakh: 0,
        criminalCases: 8,
        age: 53,
      },
    ],
    history: {
      year: 2019,
      winner: "Narendra Modi",
      winnerParty: "BJP",
      turnoutPercent: 57.13,
      marginPercent: 47.14,
    },
    alternateIDs: [
      "Aadhaar",
      "Passport",
      "Driving License",
      "PAN",
      "MNREGA Job Card",
      "Bank passbook with photo",
      "Pension document",
      "NPR smart card",
      "Government photo ID",
      "Disability ID",
    ],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
    hot: true,
  },
  {
    id: "MUM",
    name: "Mumbai South",
    state: "Maharashtra",
    stateCode: "MH",
    lon: 72.83,
    lat: 18.92,
    totalElectors: 1457423,
    pollingPhase: 5,
    pollingDate: "2024-05-20",
    countingDate: "2024-06-04",
    sittingMP: "Arvind Sawant",
    sittingMPParty: "SHS(UBT)",
    candidates2024: [
      {
        name: "Arvind Sawant",
        party: "Shiv Sena (UBT)",
        partyShort: "SHS(UBT)",
        educationLevel: "Graduate",
        declaredAssetsCrore: 5.61,
        liabilitiesLakh: 0,
        criminalCases: 1,
        age: 73,
      },
      {
        name: "Yamini Jadhav",
        party: "Shiv Sena",
        partyShort: "SHS",
        educationLevel: "12th",
        declaredAssetsCrore: 141.22,
        liabilitiesLakh: 1380,
        criminalCases: 0,
        age: 47,
      },
    ],
    history: {
      year: 2019,
      winner: "Arvind Sawant",
      winnerParty: "SHS",
      turnoutPercent: 51.59,
      marginPercent: 5.74,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "BLR",
    name: "Bangalore South",
    state: "Karnataka",
    stateCode: "KA",
    lon: 77.59,
    lat: 12.93,
    totalElectors: 2266308,
    pollingPhase: 2,
    pollingDate: "2024-04-26",
    countingDate: "2024-06-04",
    sittingMP: "Tejasvi Surya",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Tejasvi Surya",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Law graduate",
        declaredAssetsCrore: 4.10,
        liabilitiesLakh: 38,
        criminalCases: 1,
        age: 33,
      },
      {
        name: "Sowmya Reddy",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "Graduate",
        declaredAssetsCrore: 38.30,
        liabilitiesLakh: 254,
        criminalCases: 1,
        age: 38,
      },
    ],
    history: {
      year: 2019,
      winner: "Tejasvi Surya",
      winnerParty: "BJP",
      turnoutPercent: 53.73,
      marginPercent: 27.64,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "Bank passbook with photo"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "DEL",
    name: "New Delhi",
    state: "Delhi",
    stateCode: "DL",
    lon: 77.21,
    lat: 28.61,
    totalElectors: 1498768,
    pollingPhase: 6,
    pollingDate: "2024-05-25",
    countingDate: "2024-06-04",
    sittingMP: "Bansuri Swaraj",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Bansuri Swaraj",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Law graduate",
        declaredAssetsCrore: 4.10,
        liabilitiesLakh: 36,
        criminalCases: 0,
        age: 40,
      },
      {
        name: "Somnath Bharti",
        party: "Aam Aadmi Party",
        partyShort: "AAP",
        educationLevel: "Master's",
        declaredAssetsCrore: 21.68,
        liabilitiesLakh: 195,
        criminalCases: 5,
        age: 50,
      },
    ],
    history: {
      year: 2019,
      winner: "Meenakshi Lekhi",
      winnerParty: "BJP",
      turnoutPercent: 56.86,
      marginPercent: 28.65,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
    hot: true,
  },
  {
    id: "KOL",
    name: "Kolkata Dakshin",
    state: "West Bengal",
    stateCode: "WB",
    lon: 88.36,
    lat: 22.54,
    totalElectors: 1786260,
    pollingPhase: 7,
    pollingDate: "2024-06-01",
    countingDate: "2024-06-04",
    sittingMP: "Mala Roy",
    sittingMPParty: "AITC",
    candidates2024: [
      {
        name: "Mala Roy",
        party: "All India Trinamool Congress",
        partyShort: "AITC",
        educationLevel: "Graduate",
        declaredAssetsCrore: 7.71,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 70,
      },
      {
        name: "Debashree Chaudhuri",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Graduate",
        declaredAssetsCrore: 1.62,
        liabilitiesLakh: 0,
        criminalCases: 1,
        age: 64,
      },
    ],
    history: {
      year: 2019,
      winner: "Mala Roy",
      winnerParty: "AITC",
      turnoutPercent: 70.64,
      marginPercent: 13.60,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "CHN",
    name: "Chennai Central",
    state: "Tamil Nadu",
    stateCode: "TN",
    lon: 80.27,
    lat: 13.08,
    totalElectors: 1430234,
    pollingPhase: 1,
    pollingDate: "2024-04-19",
    countingDate: "2024-06-04",
    sittingMP: "Dayanidhi Maran",
    sittingMPParty: "DMK",
    candidates2024: [
      {
        name: "Dayanidhi Maran",
        party: "Dravida Munnetra Kazhagam",
        partyShort: "DMK",
        educationLevel: "Graduate",
        declaredAssetsCrore: 386.47,
        liabilitiesLakh: 14000,
        criminalCases: 5,
        age: 57,
      },
      {
        name: "Vinoj P. Selvam",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Graduate",
        declaredAssetsCrore: 5.76,
        liabilitiesLakh: 76,
        criminalCases: 1,
        age: 42,
      },
    ],
    history: {
      year: 2019,
      winner: "Dayanidhi Maran",
      winnerParty: "DMK",
      turnoutPercent: 58.22,
      marginPercent: 21.71,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "Bank passbook with photo"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "HYD",
    name: "Hyderabad",
    state: "Telangana",
    stateCode: "TG",
    lon: 78.49,
    lat: 17.39,
    totalElectors: 2278602,
    pollingPhase: 4,
    pollingDate: "2024-05-13",
    countingDate: "2024-06-04",
    sittingMP: "Asaduddin Owaisi",
    sittingMPParty: "AIMIM",
    candidates2024: [
      {
        name: "Asaduddin Owaisi",
        party: "All India Majlis-e-Ittehadul Muslimeen",
        partyShort: "AIMIM",
        educationLevel: "Law graduate (Bar-at-Law)",
        declaredAssetsCrore: 23.06,
        liabilitiesLakh: 84,
        criminalCases: 18,
        age: 54,
      },
      {
        name: "Madhavi Latha",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Graduate",
        declaredAssetsCrore: 220.07,
        liabilitiesLakh: 4500,
        criminalCases: 0,
        age: 49,
      },
    ],
    history: {
      year: 2019,
      winner: "Asaduddin Owaisi",
      winnerParty: "AIMIM",
      turnoutPercent: 44.78,
      marginPercent: 21.83,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "Pension document"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "AHM",
    name: "Ahmedabad East",
    state: "Gujarat",
    stateCode: "GJ",
    lon: 72.58,
    lat: 23.03,
    totalElectors: 1882356,
    pollingPhase: 3,
    pollingDate: "2024-05-07",
    countingDate: "2024-06-04",
    sittingMP: "Hasmukh Patel",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Hasmukh Patel",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Graduate",
        declaredAssetsCrore: 6.45,
        liabilitiesLakh: 12,
        criminalCases: 0,
        age: 60,
      },
      {
        name: "Himmatsinh Patel",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "Graduate",
        declaredAssetsCrore: 11.28,
        liabilitiesLakh: 28,
        criminalCases: 1,
        age: 56,
      },
    ],
    history: {
      year: 2019,
      winner: "Hasmukh Patel",
      winnerParty: "BJP",
      turnoutPercent: 65.68,
      marginPercent: 36.46,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "JAI",
    name: "Jaipur",
    state: "Rajasthan",
    stateCode: "RJ",
    lon: 75.79,
    lat: 26.91,
    totalElectors: 2272814,
    pollingPhase: 1,
    pollingDate: "2024-04-19",
    countingDate: "2024-06-04",
    sittingMP: "Manju Sharma",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Manju Sharma",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Graduate",
        declaredAssetsCrore: 8.61,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 60,
      },
      {
        name: "Pratap Singh Khachariyawas",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "Graduate",
        declaredAssetsCrore: 14.06,
        liabilitiesLakh: 0,
        criminalCases: 4,
        age: 60,
      },
    ],
    history: {
      year: 2019,
      winner: "Ramcharan Bohra",
      winnerParty: "BJP",
      turnoutPercent: 68.50,
      marginPercent: 36.59,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "LKO",
    name: "Lucknow",
    state: "Uttar Pradesh",
    stateCode: "UP",
    lon: 80.95,
    lat: 26.85,
    totalElectors: 2191643,
    pollingPhase: 5,
    pollingDate: "2024-05-20",
    countingDate: "2024-06-04",
    sittingMP: "Rajnath Singh",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Rajnath Singh",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Master's",
        declaredAssetsCrore: 7.62,
        liabilitiesLakh: 25,
        criminalCases: 0,
        age: 73,
      },
      {
        name: "Ravidas Mehrotra",
        party: "Samajwadi Party",
        partyShort: "SP",
        educationLevel: "Graduate",
        declaredAssetsCrore: 5.99,
        liabilitiesLakh: 0,
        criminalCases: 11,
        age: 65,
      },
    ],
    history: {
      year: 2019,
      winner: "Rajnath Singh",
      winnerParty: "BJP",
      turnoutPercent: 54.39,
      marginPercent: 41.06,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "PAT",
    name: "Patna Sahib",
    state: "Bihar",
    stateCode: "BR",
    lon: 85.14,
    lat: 25.59,
    totalElectors: 2110276,
    pollingPhase: 7,
    pollingDate: "2024-06-01",
    countingDate: "2024-06-04",
    sittingMP: "Ravi Shankar Prasad",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Ravi Shankar Prasad",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Law graduate",
        declaredAssetsCrore: 23.50,
        liabilitiesLakh: 4,
        criminalCases: 1,
        age: 69,
      },
      {
        name: "Anshul Avijit",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "Master's",
        declaredAssetsCrore: 1.84,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 39,
      },
    ],
    history: {
      year: 2019,
      winner: "Ravi Shankar Prasad",
      winnerParty: "BJP",
      turnoutPercent: 45.77,
      marginPercent: 28.43,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "GUW",
    name: "Guwahati",
    state: "Assam",
    stateCode: "AS",
    lon: 91.74,
    lat: 26.14,
    totalElectors: 1799069,
    pollingPhase: 3,
    pollingDate: "2024-05-07",
    countingDate: "2024-06-04",
    sittingMP: "Bijuli Kalita Medhi",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Bijuli Kalita Medhi",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Master's",
        declaredAssetsCrore: 4.91,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 53,
      },
      {
        name: "Mira Borthakur",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "Graduate",
        declaredAssetsCrore: 1.25,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 57,
      },
    ],
    history: {
      year: 2019,
      winner: "Queen Oja",
      winnerParty: "BJP",
      turnoutPercent: 81.61,
      marginPercent: 36.83,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "TVM",
    name: "Thiruvananthapuram",
    state: "Kerala",
    stateCode: "KL",
    lon: 76.95,
    lat: 8.52,
    totalElectors: 1455837,
    pollingPhase: 2,
    pollingDate: "2024-04-26",
    countingDate: "2024-06-04",
    sittingMP: "Shashi Tharoor",
    sittingMPParty: "INC",
    candidates2024: [
      {
        name: "Shashi Tharoor",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "PhD",
        declaredAssetsCrore: 55.46,
        liabilitiesLakh: 0,
        criminalCases: 1,
        age: 68,
      },
      {
        name: "Rajeev Chandrasekhar",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Master's",
        declaredAssetsCrore: 28.31,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 59,
      },
    ],
    history: {
      year: 2019,
      winner: "Shashi Tharoor",
      winnerParty: "INC",
      turnoutPercent: 73.74,
      marginPercent: 9.92,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "Bank passbook with photo"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "AMR",
    name: "Amritsar",
    state: "Punjab",
    stateCode: "PB",
    lon: 74.87,
    lat: 31.63,
    totalElectors: 1633320,
    pollingPhase: 7,
    pollingDate: "2024-06-01",
    countingDate: "2024-06-04",
    sittingMP: "Gurjeet Singh Aujla",
    sittingMPParty: "INC",
    candidates2024: [
      {
        name: "Gurjeet Singh Aujla",
        party: "Indian National Congress",
        partyShort: "INC",
        educationLevel: "12th",
        declaredAssetsCrore: 5.43,
        liabilitiesLakh: 0,
        criminalCases: 1,
        age: 58,
      },
      {
        name: "Taranjit Singh Sandhu",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "Master's",
        declaredAssetsCrore: 9.40,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 60,
      },
    ],
    history: {
      year: 2019,
      winner: "Gurjeet Singh Aujla",
      winnerParty: "INC",
      turnoutPercent: 57.10,
      marginPercent: 9.93,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "SRI",
    name: "Srinagar",
    state: "Jammu & Kashmir",
    stateCode: "JK",
    lon: 74.80,
    lat: 34.08,
    totalElectors: 1748043,
    pollingPhase: 4,
    pollingDate: "2024-05-13",
    countingDate: "2024-06-04",
    sittingMP: "Aga Syed Ruhullah Mehdi",
    sittingMPParty: "JKN",
    candidates2024: [
      {
        name: "Aga Syed Ruhullah Mehdi",
        party: "Jammu & Kashmir National Conference",
        partyShort: "JKN",
        educationLevel: "Graduate",
        declaredAssetsCrore: 1.41,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 56,
      },
      {
        name: "Waheed Parra",
        party: "J&K Peoples Democratic Party",
        partyShort: "JKPDP",
        educationLevel: "Master's",
        declaredAssetsCrore: 2.08,
        liabilitiesLakh: 0,
        criminalCases: 7,
        age: 36,
      },
    ],
    history: {
      year: 2019,
      winner: "Farooq Abdullah",
      winnerParty: "JKN",
      turnoutPercent: 14.43,
      marginPercent: 24.24,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "Pension document"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
  {
    id: "BHU",
    name: "Bhubaneswar",
    state: "Odisha",
    stateCode: "OD",
    lon: 85.83,
    lat: 20.30,
    totalElectors: 1789064,
    pollingPhase: 6,
    pollingDate: "2024-05-25",
    countingDate: "2024-06-04",
    sittingMP: "Aparajita Sarangi",
    sittingMPParty: "BJP",
    candidates2024: [
      {
        name: "Aparajita Sarangi",
        party: "Bharatiya Janata Party",
        partyShort: "BJP",
        educationLevel: "PhD",
        declaredAssetsCrore: 24.82,
        liabilitiesLakh: 35,
        criminalCases: 0,
        age: 60,
      },
      {
        name: "Manmath Routray",
        party: "Biju Janata Dal",
        partyShort: "BJD",
        educationLevel: "Master's",
        declaredAssetsCrore: 4.47,
        liabilitiesLakh: 0,
        criminalCases: 0,
        age: 39,
      },
    ],
    history: {
      year: 2019,
      winner: "Aparajita Sarangi",
      winnerParty: "BJP",
      turnoutPercent: 52.17,
      marginPercent: 2.42,
    },
    alternateIDs: ["Aadhaar", "Passport", "Driving License", "PAN", "MNREGA Job Card"],
    boothFinderURL: "https://electoralsearch.eci.gov.in",
  },
];

export function getConstituency(id: string): Constituency | undefined {
  return CONSTITUENCIES.find((c) => c.id === id);
}

export function constituenciesByState(): Record<string, Constituency[]> {
  const map: Record<string, Constituency[]> = {};
  for (const c of CONSTITUENCIES) {
    map[c.state] ??= [];
    map[c.state].push(c);
  }
  for (const list of Object.values(map)) {
    list.sort((a, b) => a.name.localeCompare(b.name));
  }
  return map;
}

export const CONSTITUENCY_IDS = CONSTITUENCIES.map((c) => c.id);

export function isValidConstituencyId(id: string): boolean {
  return CONSTITUENCY_IDS.includes(id);
}
